Repository Austreelis/WebsiteWhereYouAreTheHero, pull requests merged in 2022-04, with the labels that each got.

#41 Us 6 (script de création des tables
  mockups/shema_db.png
  server/migration/script0.1.0.sql
Labels: kind: US, topic: backend, US: 6

#50 Sondage
  client/pages/team.js
  common/proto.ts
  server/sockets.js
Labels: kind: improvement, topic: frontend, topic: backend, US: 3

#54 [workflows] Run eslint on PR files
  .github/workflows/eslint.yml
Labels: kind: improvement, topic: project
